ServerName localhost
DirectoryIndex index.php index.html

<VirtualHost *:80>
    ServerName localhost

    DocumentRoot /srv/xserver/public_html

    <Directory /srv/xserver/public_html>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName book.fit-sc.test

    DocumentRoot /srv/xserver/public_html/book

    <Directory /srv/xserver/public_html/book>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName admin.book.fit-sc.test

    DocumentRoot /srv/xserver/public_html/admin.book

    <Directory /srv/xserver/public_html/admin.book>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName set.book.fit-sc.test

    DocumentRoot /srv/xserver/public_html/set.book

    <Directory /srv/xserver/public_html/set.book>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName forms.fit-sc.test

    DocumentRoot /srv/xserver/public_html/forms

    <Directory /srv/xserver/public_html/forms>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName admin.forms.fit-sc.test

    DocumentRoot /srv/xserver/public_html/admin.forms

    <Directory /srv/xserver/public_html/admin.forms>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName lend.fit-sc.test 

    DocumentRoot /srv/xserver/public_html/lend

    <Directory /srv/xserver/public_html/lend>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName account.fit-sc.test

    DocumentRoot /srv/xserver/public_html/account

    <Directory /srv/xserver/public_html/account>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName mail.fit-sc.test

    DocumentRoot /srv/xserver/public_html/mail

    <Directory /srv/xserver/public_html/mail>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

<VirtualHost *:80>
    ServerName kintone.fit-sc.test

    DocumentRoot /srv/xserver/public_html/kintone

    <Directory /srv/xserver/public_html/kintone>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>